### PR TITLE
Fix memory leak in `CCC_DebugFonts`

### LINKED ISSUE #1123: Fix memory leak in CCC_DebugFonts
https://github.com/OpenXRay/xray-16/blob/14a049e809c923488f77079d5d722198736d08fd/src/xrGame/console_commands.cpp#L1058

### PR DESCRIPTION
**Pull request by AMS21**
Not sure about the projects conventions for naming or handling OOM. But the original code also didn't care about `xr_new` potentially returning null.

This patch also prevents you from opening multiple font debug menus at the same time.

This fixes #1123

### CODE REVIEW

File: src/xrGame/console_commands.cpp [hunk 1]
```diff
@@ -1080,11 +1080,17 @@ class CCC_DebugFonts : public IConsole_Command
...
-        // BUG: leak
-        (xr_new<CUIDebugFonts>())->ShowDialog(true);
+        if (!ui)
+            ui = xr_new<CUIDebugFonts>();
+
+        ui->ShowDialog(true);
     }
+
+private:
+    CUIDebugFonts* ui;
```
Comment (Xottab-DUTY) [inline src/xrGame/console_commands.cpp]: Let's name it `m_ui` to look it a bit better

File: src/xrGame/console_commands.cpp [hunk 2]
```diff
@@ -1080,11 +1080,17 @@ class CCC_DebugFonts : public IConsole_Command
 {
 public:
     CCC_DebugFonts(LPCSTR N) : IConsole_Command(N) { bEmptyArgsHandled = true; }
+    ~CCC_DebugFonts() { xr_free(ui); }
     virtual void Execute(LPCSTR args)
     {
-        // BUG: leak
-        (xr_new<CUIDebugFonts>())->ShowDialog(true);
+        if (!ui)
+            ui = xr_new<CUIDebugFonts>();
```
Comment (Xottab-DUTY) [inline src/xrGame/console_commands.cpp]: With this solution, there's an issue: CUIDebugFonts calls xr_delete on itself when you press Escape, so CCC_DebugFonts class will store an invalid pointer after the memory deletion.

**Review by Xottab-DUTY — CHANGES_REQUESTED** [review]

File: src/xrGame/console_commands.cpp (hunk 2 above)
Comment (Hrusteckiy) [reply src/xrGame/console_commands.cpp:1087]: Is it possible to draw more than one instance of one font type? I'd like to draw letterica18 in two places of screen for example.

**Comment by Hrusteckiy** [comment]
Is it possible to draw more than one instance of one font type? I'd like to draw letterica18 in two places of screen for example.

**Comment by Xottab-DUTY** [comment]
> Is it possible to draw more than one instance of one font type? I'd like to draw letterica18 in two places of screen for example.

This PR is not related to fonts, it's related to fonts debugger class :D
But yes, you can, just create new instance of a font.

File: src/xrGame/console_commands.cpp (hunk 2 above)
Comment (AMS21) [reply src/xrGame/console_commands.cpp]: I've tried to test this but using `debug_fonts` multiple times seems to work without crashing.
Also looking at the code for `HideDialog` I don't see a deallocation but I may be missing something here.

File: src/xrGame/console_commands.cpp [hunk 3]
```diff
@@ -1080,11 +1080,17 @@ class CCC_DebugFonts : public IConsole_Command
 {
 public:
     CCC_DebugFonts(LPCSTR N) : IConsole_Command(N) { bEmptyArgsHandled = true; }
+    ~CCC_DebugFonts() { xr_free(m_ui); }
```
Comment (Xottab-DUTY) [inline src/xrGame/console_commands.cpp]:
```suggestion

    ~CCC_DebugFonts()
    {
        xr_free(m_ui);
    }

```

**Comment by Xottab-DUTY** [comment]
Thanks!

File: src/xrGame/console_commands.cpp (hunk 2 above)
Comment (Xottab-DUTY) [reply src/xrGame/console_commands.cpp]: Ohhh, if it was calling xr_delete on itself, then there would be no memory leak, but there was no xr_delete call.
I got mixed up a bit))

File: src/xrGame/console_commands.cpp [hunk 4]
```diff
@@ -1080,11 +1080,22 @@ class CCC_DebugFonts : public IConsole_Command
...
-        // BUG: leak
-        (xr_new<CUIDebugFonts>())->ShowDialog(true);
+        if (!m_ui)
+            m_ui = xr_new<CUIDebugFonts>();
+
+        m_ui->ShowDialog(true);
     }
+
+private:
+    CUIDebugFonts* m_ui;
```
Comment (Masterkatze) [inline src/xrGame/console_commands.cpp:1098]: `xr_unique_ptr`?

Comment (AMS21) [reply src/xrGame/console_commands.cpp:1098]: That would be even better IMO
