### PR TITLE
Some PVS-Studio warning fixes (part 4)

### LINKED ISSUE #4: Get Dedicated Server Running
Dedicated server appears to crash when run with _Debug_ configuration.  From @nitrocaster the following log output is common:

```
"ID3DDepthStencilState #%d created"
```

And may be of use. 

When posting debug logs, please use some paste service like pastebin, please.

### PR DESCRIPTION
**Pull request by dimhotepus**
Some missed warning fixes from PVS-Studio static analyzer tool.

### CODE REVIEW

**Comment by dimhotepus** [comment]
@Xottab-DUTY Could you please help me to find out why Linux builds fail on `xrGame` linking?

May be i should add some linker tracing option to get exact error message?

**Comment by Xottab-DUTY** [comment]
@dimhotepus it compiles and links xrGame, but fails on xrRender_GL compilation which I broke just yesterday... And you have rebased to the latest commits :)

**Comment by Xottab-DUTY** [comment]
@dimhotepus I fixed it.

**Comment by dimhotepus** [comment]
> @dimhotepus I fixed it.

Thank you! I'll rebase tomorrow when be at home. Could you, please, check i haven't missed smth?

File: src/xrUICore/ListWnd/UIListItemEx.cpp [hunk 1]
```diff
@@ -11,11 +11,10 @@
 
 #include "UIListItemEx.h"
 
-CUIListItemEx::CUIListItemEx()
+CUIListItemEx::CUIListItemEx() : m_dwSelectionColor(color_argb(200, 95, 82, 74))
 {
     //.	InitTexture("ui\\hud_map_point");
-    //.	SetStretchTexture(true);
-    m_dwSelectionColor = color_argb(200, 95, 82, 74);
+    //.	SetStretchTexture(true);
```
Comment (Xottab-DUTY) [inline src/xrUICore/ListWnd/UIListItemEx.cpp]: Occasional indentation on the right side
```suggestion
    //.	SetStretchTexture(true);
```

File: src/xrUICore/Lines/UILine.cpp [hunk 2]
```diff
@@ -23,9 +23,8 @@ CUILine::~CUILine()
 }
 
 CUILine::CUILine(const CUILine& other)
+    : m_subLines(other.m_subLines), m_tmpLine(NULL)
```
Comment (Xottab-DUTY) [inline src/xrUICore/Lines/UILine.cpp]:
```suggestion
    : m_subLines(other.m_subLines), m_tmpLine(nullptr) 
```

File: src/xrPhysics/Geometry.cpp [hunk 3]
```diff
@@ -590,7 +588,7 @@ void CSphereGeom::set_build_position(const Fvector& ref_point)
     dGeomSetPosition(geom(), local_position[0], local_position[1], local_position[2]);
 }
 
-CCylinderGeom::CCylinderGeom(const Fcylinder& cyl) { m_cylinder = cyl; }
+CCylinderGeom::CCylinderGeom(const Fcylinder& cyl) : m_cylinder(cyl) {}
```
Comment (Xottab-DUTY) [inline src/xrPhysics/Geometry.cpp]:
```suggestion
CCylinderGeom::CCylinderGeom(const Fcylinder& cyl) : m_cylinder(cyl) { }
```

File: src/xrPhysics/Geometry.cpp [hunk 4]
```diff
@@ -559,7 +557,7 @@ void CBoxGeom::set_build_position(const Fvector& ref_point)
     dGeomSetRotation(geom(), R);
 }
 
-CSphereGeom::CSphereGeom(const Fsphere& sphere) { m_sphere = sphere; }
+CSphereGeom::CSphereGeom(const Fsphere& sphere) : m_sphere(sphere) {}
```
Comment (Xottab-DUTY) [inline src/xrPhysics/Geometry.cpp]:
```suggestion
CSphereGeom::CSphereGeom(const Fsphere& sphere) : m_sphere(sphere) { }
```

File: src/xrPhysics/Geometry.cpp [hunk 5]
```diff
@@ -405,7 +403,7 @@ void CODEGeom::destroy()
     m_geom_transform = NULL;
 }
 
-CBoxGeom::CBoxGeom(const Fobb& box) { m_box = box; }
+CBoxGeom::CBoxGeom(const Fobb& box) : m_box(box) {}
```
Comment (Xottab-DUTY) [inline src/xrPhysics/Geometry.cpp]:
```suggestion
CBoxGeom::CBoxGeom(const Fobb& box) : m_box(box) { }
```

File: src/xrGame/ui/UIRankIndicator.cpp [hunk 6]
```diff
@@ -3,7 +3,7 @@
 #include "UIXmlInit.h"
 #include "xrUICore/Static/UIStatic.h"
 
-CUIRankIndicator::CUIRankIndicator() { m_current = u8(-1); }
+CUIRankIndicator::CUIRankIndicator() : m_current(u8(-1)) {}
```
Comment (Xottab-DUTY) [inline src/xrGame/ui/UIRankIndicator.cpp]:
```suggestion
CUIRankIndicator::CUIRankIndicator() : m_current(u8(-1)) { }
```

File: src/xrGame/relation_registry_fights.cpp [hunk 7]
```diff
@@ -10,13 +10,9 @@
 //////////////////////////////////////////////////////////////////////////
 
 RELATION_REGISTRY::FIGHT_DATA::FIGHT_DATA()
+    : attacker(0xffffU), defender(0xffffU), total_hit(0), time(0), time_old(0),
```
Comment (Xottab-DUTY) [inline src/xrGame/relation_registry_fights.cpp]:
```suggestion
    : attacker(u16(-1)), defender(u16(-1)), total_hit(0), time(0), time_old(0),
```

File: src/xrGame/Torch.cpp [hunk 8]
```diff
@@ -30,23 +30,18 @@ static const float OPTIMIZATION_DISTANCE = 100.f;
 static bool stalker_use_dynamic_lights = false;
 
 CTorch::CTorch(void)
+    : fBrightness(1.f), lanim(nullptr), guid_bone(BI_NONE), m_delta_h(0),
+      m_switched_on(false), light_render(GEnv.Render->light_create()),
+      light_omni(GEnv.Render->light_create()), glow_render(GEnv.Render->glow_create()),
+      m_bNightVisionEnabled(false), m_bNightVisionOn(false), m_night_vision(nullptr)
```
Comment (Xottab-DUTY) [inline src/xrGame/Torch.cpp]: Changed formatting.
```suggestion
    : fBrightness(1.f), lanim(nullptr), guid_bone(BI_NONE),
      m_delta_h(0), m_switched_on(false),
      light_render(GEnv.Render->light_create()),
      light_omni  (GEnv.Render->light_create()),
      glow_render (GEnv.Render->glow_create()),
      m_bNightVisionEnabled(false), m_bNightVisionOn(false), m_night_vision(nullptr)
```

File: src/xr_3da/AccessibilityShortcuts.hpp [hunk 9]
```diff
@@ -12,17 +12,10 @@ class AccessibilityShortcuts
 
 public:
     AccessibilityShortcuts()
+        : screensaverState(false),
+          stickyKeys{sizeof(stickyKeys)}, filterKeys{sizeof(filterKeys)}, toggleKeys{sizeof(toggleKeys)},
```
Comment (Xottab-DUTY) [inline src/xr_3da/AccessibilityShortcuts.hpp]:
```suggestion
          stickyKeys{ sizeof(stickyKeys) }, filterKeys{ sizeof(filterKeys) }, toggleKeys{ sizeof(toggleKeys) },
```

File: src/xrNetServer/NET_Client.cpp [hunk 10]
```diff
@@ -330,20 +330,13 @@ void IPureClient::_Recieve(const void* data, u32 data_size, u32 /*param*/)
 //==============================================================================
 
 IPureClient::IPureClient(CTimer* timer)
-    : net_Statistic(timer)
+    : device_timer(timer), NET(nullptr), net_Address_device(nullptr), net_Address_server(nullptr),
 #ifdef CONFIG_PROFILE_LOCKS
-    , net_csEnumeration(MUTEX_PROFILE_ID(IPureClient::net_csEnumeration))
+      , net_csEnumeration(MUTEX_PROFILE_ID(IPureClient::net_csEnumeration)),
```
Comment (Xottab-DUTY) [inline src/xrNetServer/NET_Client.cpp]:
```suggestion
    , net_csEnumeration(MUTEX_PROFILE_ID(IPureClient::net_csEnumeration)),
```

File: src/xrD3D9-Null/IDirect3DIndexBuffer9.cpp [hunk 11]
```diff
@@ -8,23 +8,13 @@ const GUID DECLSPEC_SELECTANY IID_IDirect3DIndexBuffer9;
 
 xrIDirect3DIndexBuffer9::xrIDirect3DIndexBuffer9(
     IDirect3DDevice9* pIDirect3DDevice9, UINT iLength, DWORD iUsage, D3DFORMAT iFormat, D3DPOOL iPool)
-    : m_refCount(0)
+    : m_refCount(0), m_pIDirect3DDevice9(pIDirect3DDevice9)
+//#ifdef D3D_DEBUG_INFO
+      , Name(nullptr), Length(iLength), Usage(iUsage), Format(iFormat), Pool(iPool),
```
Comment (Xottab-DUTY) [inline src/xrD3D9-Null/IDirect3DIndexBuffer9.cpp]:
```suggestion
    , Name(nullptr), Length(iLength), Usage(iUsage), Format(iFormat), Pool(iPool),
```

**Review by Xottab-DUTY — COMMENTED** [review]
Some changes require some more analysis, so I didn't finished the review yet

File: src/xrGame/relation_registry_fights.cpp (hunk 7 above)
Comment (dimhotepus) [reply src/xrGame/relation_registry_fights.cpp]: Done.

File: src/xrD3D9-Null/IDirect3DIndexBuffer9.cpp (hunk 11 above)
Comment (dimhotepus) [reply src/xrD3D9-Null/IDirect3DIndexBuffer9.cpp]: Done

File: src/xrNetServer/NET_Client.cpp (hunk 10 above)
Comment (dimhotepus) [reply src/xrNetServer/NET_Client.cpp]: Done

File: src/xrPhysics/Geometry.cpp (hunk 5 above)
Comment (dimhotepus) [reply src/xrPhysics/Geometry.cpp]: Done

File: src/xrPhysics/Geometry.cpp (hunk 3 above)
Comment (dimhotepus) [reply src/xrPhysics/Geometry.cpp]: Done

File: src/xrUICore/Lines/UILine.cpp (hunk 2 above)
Comment (dimhotepus) [reply src/xrUICore/Lines/UILine.cpp]: Done.

File: src/xrGame/Torch.cpp (hunk 8 above)
Comment (dimhotepus) [reply src/xrGame/Torch.cpp]: Done.

File: src/xrGame/ui/UIRankIndicator.cpp (hunk 6 above)
Comment (dimhotepus) [reply src/xrGame/ui/UIRankIndicator.cpp]: Done

File: src/xrPhysics/Geometry.cpp (hunk 4 above)
Comment (dimhotepus) [reply src/xrPhysics/Geometry.cpp]: Done.

File: src/xrUICore/ListWnd/UIListItemEx.cpp (hunk 1 above)
Comment (dimhotepus) [reply src/xrUICore/ListWnd/UIListItemEx.cpp]: Done.

File: src/xr_3da/AccessibilityShortcuts.hpp (hunk 9 above)
Comment (dimhotepus) [reply src/xr_3da/AccessibilityShortcuts.hpp]: Done.

File: src/xrCore/LocatorAPI.cpp [hunk 12]
```diff
@@ -612,8 +612,7 @@ void CLocatorAPI::ProcessOne(pcstr path, const _finddata_t& entry)
             return;
         if (0 == xr_strcmp(entry.name, ".."))
             return;
-        if (path[xr_strlen(path) - 1] != _DELIMITER || path[xr_strlen(path) - 1] != '/')
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.cpp]: @eagleivg, do you remember why you have added this check?

Comment (Xottab-DUTY) [reply src/xrCore/LocatorAPI.cpp]: Engine filesystem has strong requirements on path correctness.
```
Path can be delimited only by a single delimiter.
Delimiters cannot be mixed. (it's either \ or /, but not both)
Folder path must always end with delimiter.

Correct path on Windows: folder\\      (ends by single backslash only)
Correct path on Windows: folder\\file  (delimited by single backslash only)

Correct path on Linux:   folder/       (ends by single forward slash only)
Correct path on Linux:   folder/file   (delimited by single forward slash only)

Wrong path on Windows:   folder
Wrong path on Windows:   folder/file
Wrong path on Windows:   folder//file
Wrong path on Windows:   folder\\\\file

Wrong path on Linux:     folder
Wrong path on Linux:     folder//file
Wrong path on Linux:	 folder\\file
Wrong path on Linux:	 folder\\\\file
etc...
```

**Comment by dimhotepus** [comment]
@Xottab-DUTY Looks like transient nuget failure, may be trigger rebuild?

File: src/xrCore/LocatorAPI.cpp (hunk 12 above)
Comment (dimhotepus) [reply src/xrCore/LocatorAPI.cpp]: So always adding delimiter for directory looks good.
I remember when we replaced logical operator with `&&`, engine fails to load some files, so looks like condition is really expected to be `true`.

Comment (Xottab-DUTY) [reply src/xrCore/LocatorAPI.cpp]: Not exactly. It looks like this condition is always true on Windows, but Linux filesystem (not the engine one! I mean OS internals) can add a delimiter before we enter this function. Removing this check will result in a double delimiter.

Comment (dimhotepus) [reply src/xrCore/LocatorAPI.cpp]: Hm, for me it looks independent of OS:
```
if (path[xr_strlen(path) - 1] != _DELIMITER || path[xr_strlen(path) - 1] != '/')
```
to simplify reasoning, replace `path[xr_strlen(path) - 1]` with `A`:
```
if (A != _DELIMITER || A != '/')
```
replace `_DELIMITER` with `2` and '/' with `3` (`_DELIMITER` now is '\\'):
```
if (A != 2 || A != 3)
```
so this condition is always `true`, independent of `A` value.

Do you mean `_DELIMITER` is generated and OS-dependent (`/` for Unix-like or Mac)?
If so, may be replace condition with:
```
#if defined(_WIN32)
  xr_strcat(N, DELIMITER);
#else
  if (A != _DELIMITER)
    xr_strcat(N, DELIMITER);
#endif

?

Comment (dimhotepus) [reply src/xrCore/LocatorAPI.cpp]: > Not exactly. It looks like this condition is always true on Windows, but Linux filesystem (not the engine one! I mean OS internals) can add a delimiter before we enter this function. Removing this check will result in a double delimiter.

Removed this commit :)

**Comment by dimhotepus** [comment]
@Xottab-DUTY Could you, please, continue to review the changes? Ready to fix if smth'll be found.

**Comment by Xottab-DUTY** [comment]
@dimhotepus, I'm really sorry for the huge delay in the reviewing the PR! Was a little bit unable to review it properly. Will try to do it as soon as possible.

**Comment by dimhotepus** [comment]
> @dimhotepus, I'm really sorry for the huge delay in the reviewing the PR! Was a little bit unable to review it properly. Will try to do it as soon as possible.

No problem, thank you for clarification and help!

Sorry for a huge PR, may be i can help by splitting suspicious or hard to guess changes into distinct PRs?

File: src/xrCore/LocatorAPI.cpp [hunk 13]
```diff
@@ -1037,7 +1037,7 @@ FileStatus CLocatorAPI::exist(pcstr fn, FSType fsType /*= FSType::Virtual*/)
     if ((fsType | FSType::External) == FSType::External)
     {
         struct stat buffer;
-        buffer.st_size;
+        [[maybe_unused]] const auto& st_size = buffer.st_size;
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.cpp]: If think we don't even need this :)

File: src/xrAICore/Navigation/vertex_allocator_fixed_inline.h [hunk 14]
```diff
@@ -15,7 +15,7 @@
 #define CFixedVertexAllocator CVertexAllocatorFixed<ReserveSize>::CDataStorage<TCompoundVertex>
 
 TEMPLATE_SPECIALIZATION
-inline CFixedVertexAllocator::CDataStorage() { m_vertices.resize(ReserveSize); }
+inline CFixedVertexAllocator::CDataStorage() : m_vertex_count(-1) { m_vertices.resize(ReserveSize); }
```
Comment (Xottab-DUTY) [inline src/xrAICore/Navigation/vertex_allocator_fixed_inline.h]:
```suggestion
inline CFixedVertexAllocator::CDataStorage() : m_vertex_count(u32(-1)) { m_vertices.resize(ReserveSize); }
```

File: src/xrAICore/Navigation/level_graph.cpp [hunk 15]
```diff
@@ -11,6 +11,7 @@
 #include "xrEngine/profiler.h"
 
 CLevelGraph::CLevelGraph(const char* fileName)
+    : m_level_id(GameGraph::_LEVEL_ID(-1))
```
Comment (Xottab-DUTY) [inline src/xrAICore/Navigation/level_graph.cpp:14]: We can leave this change in this pull request.

**Review by Xottab-DUTY — COMMENTED** [review]
> Sorry for a huge PR

Not so big :)

> may be i can help by splitting suspicious or hard to guess changes into distinct PRs?

Yes! For now it is probably better to move the changes to `problem_solver_inline.h` and `level_graph.cpp` to another pull request. All other files are checked except these two...

File: src/xrCore/LocatorAPI.cpp (hunk 13 above)
Comment (dimhotepus) [reply src/xrCore/LocatorAPI.cpp]: Done

File: src/xrAICore/Navigation/vertex_allocator_fixed_inline.h (hunk 14 above)
Comment (dimhotepus) [reply src/xrAICore/Navigation/vertex_allocator_fixed_inline.h]: Done

File: src/xrAICore/Navigation/level_graph.cpp (hunk 15 above)
Comment (dimhotepus) [reply src/xrAICore/Navigation/level_graph.cpp:14]: Well, done).

Comment (Xottab-DUTY) [reply src/xrAICore/Navigation/level_graph.cpp:14]: @dimhotepus, but you didn't moved **other** changes to this file and `problem_solver_inline.h` to another pull request

File: src/xrAICore/Navigation/level_graph.cpp [hunk 16]
```diff
@@ -218,7 +219,7 @@ u32 CLevelGraph::vertex_id(const Fvector& position) const
             if (_y <= position.y)
             {
                 // so, new node is under the specified position
-                if (position.y - _y < position.y - y)
+                if (_y > y)
```
Comment (Xottab-DUTY) [inline src/xrAICore/Navigation/level_graph.cpp]: This change is not explained, so I can't understand why it's changed.

**Comment by Xottab-DUTY** [comment]
Okay, so I just checked `problem_solver_inline.h` and we don't need to move changes from it to another pull request...
Now, only file I need to check is `level_graph.cpp`. I don't understand the change and I'm not sure if the simplified expression won't break something.

File: src/xrAICore/Navigation/level_graph.cpp (hunk 16 above)
Comment (dimhotepus) [reply src/xrAICore/Navigation/level_graph.cpp]: I've tried to simplify the expressions, consider:
```
if (position.y - _y < position.y - y) {
```

assume `position.y` is `A`:

```
const auto A = position.y;
if (A - _y < A - y) {
```

then we can simplify expression using algebra rules (subtract `A` from both sides):

```
if (- _y < - y) {
```

then multiply both sides on `-1`, which reverts expression sign (consider `1 < 2`, than `-1 > -2`):

```
if (-1 * -_y > -1 * -y) {
```

and, finally, simplify expression by partial evaluation:

```
if (_y > y) {
```

Comment (dimhotepus) [reply src/xrAICore/Navigation/level_graph.cpp]: @Xottab-DUTY If change is too suspicious, and explanation is not well, i can remove the change, ok?

Comment (Xottab-DUTY) [reply src/xrAICore/Navigation/level_graph.cpp]: @dimhotepus the explanation is very well. That's just me being too neat/careful. I want to see the values in-game, but I won't be able to do that till New Year. Sorry for taking too long on this PR.

So, yes, it would be better to move this particular change to another pull request. Since everything is reviewed except this, the PR can be merged straightforward if we remove this.
Also, if you can, consider to just remove the commit 553f8ab12f1a107a6c6edee2ee854ce594e0471d via rebase instead of making a reverting commit. Thank you!

Comment (dimhotepus) [reply src/xrAICore/Navigation/level_graph.cpp]: Not a problem, thank you for review and help! 

I'll remove this one https://github.com/OpenXRay/xray-16/commit/553f8ab12f1a107a6c6edee2ee854ce594e0471d as you suggested.

**Comment by Xottab-DUTY** [comment]
Oh, today I pushed a commit that broke the head branch from compilation. Will fix it.

**Comment by Xottab-DUTY** [comment]
@dimhotepus `xd_dev` should be fixed now.

**Comment by dimhotepus** [comment]
> @dimhotepus `xd_dev` should be fixed now.

Thank you! I've rebased, waiting for build to succeed

**Review by Xottab-DUTY — APPROVED** [review]

**Comment by Xottab-DUTY** [comment]
Thank you for your patience! :smiley:
