### PR TITLE
A set of small fixes to be able to run the game on macOS (fixes #1104)

### LINKED ISSUE #1104: Run the game on macOS
Although the engine can be built successfully on macOS, the game won't run.

### PR DESCRIPTION
**Pull request by Lnd-stoL**
These fixes are essential for running the game on macOS.
With this set of fixes I was able to successfully run the game on M1 Pro Mac without severe glitches (though there are some rendering related error messages in logs).

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
Wow maan, many thanks! Especially for the first two commits! These `&*` dereferences and nitpicky problems like missing virtual destructors were pain in the ***!

File: src/xrGame/ui/UIGameTutorial.h [hunk 1]
```diff
@@ -26,6 +26,7 @@ class CUISequencer : public pureFrame, public pureRender, public IInputReceiver
 
 public:
     IInputReceiver* m_pStoredInputReceiver;
+    virtual ~CUISequencer() = default;
     CUISequencer();
```
Comment (Xottab-DUTY) [inline src/xrGame/ui/UIGameTutorial.h]: For the consistency, it's better to place the destructor after the constructor.
```suggestion

    CUISequencer();
    virtual ~CUISequencer() = default;

```

File: src/xrServerEntities/object_item_abstract.h [hunk 2]
```diff
@@ -21,6 +21,7 @@ class CObjectItemAbstract
     shared_str m_script_clsid;
 
 public:
+    virtual ~CObjectItemAbstract() = default;
     IC CObjectItemAbstract(const CLASS_ID& clsid, LPCSTR script_clsid);
```
Comment (Xottab-DUTY) [inline src/xrServerEntities/object_item_abstract.h]: For the consistency, it's better to place the destructor after the constructor.
```suggestion
    IC CObjectItemAbstract(const CLASS_ID& clsid, LPCSTR script_clsid);
    virtual ~CObjectItemAbstract() = default;

```

File: src/Layers/xrRenderGL/glSH_RT.cpp [hunk 3]
```diff
@@ -52,15 +52,18 @@ void CRT::create(LPCSTR Name, u32 w, u32 h, D3DFORMAT f, u32 SampleCount /*= 1*/
...
+    {
+        // Get caps
+        GLint max_width, max_height;
+        CHK_GL(glGetIntegerv(GL_MAX_FRAMEBUFFER_WIDTH, &max_width));
+        CHK_GL(glGetIntegerv(GL_MAX_FRAMEBUFFER_HEIGHT, &max_height));
+
+        // Check width-and-height of render target surface
+        // XXX: While seemingly silly, assert w/h are positive?
+        if (w > u32(max_width)) return;
+        if (h > u32(max_height)) return;
```
Comment (Xottab-DUTY) [inline src/Layers/xrRenderGL/glSH_RT.cpp]: Let's fix the code style by the way :)
```suggestion
        if (w > u32(max_width))
            return;
        if (h > u32(max_height))
            return;
```

File: src/Layers/xrRenderPC_GL/rgl_shaders.cpp [hunk 4]
```diff
@@ -411,7 +411,12 @@ HRESULT CRender::shader_compile(pcstr name, IReader* fs, pcstr pFunctionName,
     appendShaderOption(o.gbuffer_opt, "GBUFFER_OPTIMIZATION", "1");
 
     // Shader Model 4.1
+#ifndef __APPLE__
     appendShaderOption(o.dx11_sm4_1, "SM_4_1", "1");
+    // Despite the fact that glsl 4.1 is claimed to be supported on macOS,
+    // the issue is that gatherTextureOffset requires compile-time constant offset argument.
+    // So it is more handy to disable its use for mac as for now.
```
Comment (Xottab-DUTY) [inline src/Layers/xrRenderPC_GL/rgl_shaders.cpp:418]: Maybe, we can provide compile-time offset later? (after some investigation, if this is possible)
Maybe we can leave a TODO here?
```suggestion
    // So it is more handy to disable its use for mac as for now.
    // XXX: investigate if we can provide compile-time constant offset
```

**Review by Xottab-DUTY — CHANGES_REQUESTED** [review]
Thanks again!
There are few small remarks and compilation fails on Windows x64, though.

**Comment by Xottab-DUTY** [comment]
@Lnd-stoL, you also maybe want to look at #923. Maybe, you'll find something useful there.

File: src/Layers/xrRenderPC_GL/rgl_shaders.cpp (hunk 4 above)
Comment (Lnd-stoL) [reply src/Layers/xrRenderPC_GL/rgl_shaders.cpp:418]: Unfortunately, its not so easy to provide compile-time constant, cause the typical use case of textureGatherOffset is in for loops (using loop counter as offset parameter). 
The solution could be loop unrolling, but it is not supported by OpenGL4.1.

So, the only option I see is "manual" loop unrolling producing code like

```
  float4 s_dmap_gpp[16];
  s_dmap_gpp[0] = textureGatherOffset( s_dmap, tc.xy, int2( -3, -3 ) );
  s_dmap_gpp[1] = textureGatherOffset( s_dmap, tc.xy, int2( -3, -1 ) );
  s_dmap_gpp[2] = textureGatherOffset( s_dmap, tc.xy, int2( -3,  1 ) );
  s_dmap_gpp[3] = textureGatherOffset( s_dmap, tc.xy, int2( -3,  3 ) );

  s_dmap_gpp[4] = textureGatherOffset( s_dmap, tc.xy, int2( -1, -3 ) );
  s_dmap_gpp[5] = textureGatherOffset( s_dmap, tc.xy, int2( -1, -1 ) );
  s_dmap_gpp[6] = textureGatherOffset( s_dmap, tc.xy, int2( -1,  1 ) );
  s_dmap_gpp[7] = textureGatherOffset( s_dmap, tc.xy, int2( -1,  3 ) );

  s_dmap_gpp[8] = textureGatherOffset( s_dmap, tc.xy, int2( 1, -3 ) );
  s_dmap_gpp[9] = textureGatherOffset( s_dmap, tc.xy, int2( 1, -1 ) );
  s_dmap_gpp[10] = textureGatherOffset( s_dmap, tc.xy, int2( 1,  1 ) );
  s_dmap_gpp[11] = textureGatherOffset( s_dmap, tc.xy, int2( 1,  3 ) );          

  s_dmap_gpp[12] = textureGatherOffset( s_dmap, tc.xy, int2( 3, -3 ) );
  s_dmap_gpp[13] = textureGatherOffset( s_dmap, tc.xy, int2( 3, -1 ) );
  s_dmap_gpp[14] = textureGatherOffset( s_dmap, tc.xy, int2( 3,  1 ) );
  s_dmap_gpp[15] = textureGatherOffset( s_dmap, tc.xy, int2( 3,  3 ) );   
```

This boilerplate code can be generated in C++, by the way.
Don't know if the approach is acceptable by the community.

**Comment by Lnd-stoL** [comment]
> There are few small remarks and compilation fails on Windows x64, though.

They seem to be fixes by now.

File: src/Layers/xrRender/r__dsgraph_render.cpp [hunk 5]
```diff
@@ -46,7 +47,7 @@ void R_dsgraph_structure::r_dsgraph_render_graph(u32 _priority)
         auto& map = mapNormalPasses[_priority][iPass];
 
         map.get_any_p(nrmPasses);
-        std::sort(nrmPasses.begin(), nrmPasses.end(), cmp_pass<mapNormal_T::value_type*>);
+        std::stable_sort(nrmPasses.begin(), nrmPasses.end(), cmp_pass<mapNormal_T::value_type*>);
```
Comment (Xottab-DUTY) [inline src/Layers/xrRender/r__dsgraph_render.cpp]: Why sort algorithm and comparator was changed? What are the results of these changes?

File: src/xrGame/reward_event_handler.h [hunk 6]
```diff
@@ -11,7 +11,7 @@ class reward_event_handler
 {
 public:
     reward_event_handler(game_state_accumulator* pstate) : m_player_state_accum(pstate) {}
-    ~reward_event_handler(){};
+    virtual ~reward_event_handler(){};
```
Comment (Xottab-DUTY) [inline src/xrGame/reward_event_handler.h:14]: Let's let the compiler to generate everything else.
```suggestion
    virtual ~reward_event_handler() = default;
```

File: src/xrCore/xrMemory.cpp [hunk 7]
```diff
@@ -112,7 +112,7 @@ size_t xrMemory::mem_usage()
         CloseHandle(h);
     }
     return pmc.PagefileUsage;
-#elif defined(XR_PLATFORM_LINUX)
+#elif defined(XR_PLATFORM_LINUX) || defined(XR_PLATFORM_APPLE)
     struct rusage ru;
     getrusage(RUSAGE_SELF, &ru);
     return (size_t)ru.ru_maxrss;
```
Comment (Xottab-DUTY) [inline src/xrCore/xrMemory.cpp:118]: We can just by the way prevent missing return from function for possible future platforms.
```suggestion
    return (size_t)ru.ru_maxrss;
#else
#   error Select or add an implementation for your platform
```

File: src/Layers/xrRender/r__dsgraph_render.cpp (hunk 5 above)
Comment (Lnd-stoL) [reply src/Layers/xrRender/r__dsgraph_render.cpp]: As far as I understand, the comparator contained logical error leading to UB in resulting sort algorithm, causing crashes (somehow) on my Mac machine.
The error is that it returns true for two equal arguments, that means cmp(a, b) == cmp(b, a) if a.equal(b) or, in the other words, a < b && b < a is true. Such comparator behavior doesn't meet the C++ standard criteria https://en.cppreference.com/w/cpp/named_req/Compare and doesn't make much sense (how can we order two items if one orders before another, but another is also before the one).
Looking at the code I made a guess that the intent was actually to sort SPass'es based on ssa, but doesn't touch equal ones (though I didn't figure out, why there can be equal SPass'es and can they have different ssa). Fell free to correct me if I got it wrong.
As for stable sort, I just followed the intuition that it's always better not to mess up rendering order from frame to frame (which may cause kind of flickering). So, knowing there can be equal items in the nrmPasses I decided to elide possible sorting instability factor.

File: src/xrGame/reward_event_handler.h (hunk 6 above)
Comment (Lnd-stoL) [reply src/xrGame/reward_event_handler.h:14]: Ok, I just tried to limit the changes to the required minimum.

File: src/Layers/xrRenderPC_GL/rgl_shaders.cpp (hunk 4 above)
Comment (Lnd-stoL) [reply src/Layers/xrRenderPC_GL/rgl_shaders.cpp:418]: Let me know if it is acceptable approach or maybe there are some more experienced OpenGL people here, who can give a piece of advice.

File: src/Layers/xrRender/r__dsgraph_render.cpp (hunk 5 above)
Comment (Xottab-DUTY) [reply src/Layers/xrRender/r__dsgraph_render.cpp]: Maybe it's better to move this particular change to another pull request... Or, @vTurbine, can you tell if this change in comparator and stable sort is ok or even better than what we have currently?

Original engine code was sorting the scene graph in a special way to minimize state changes. I simplified the code to make SPass look like PSO (so we can add DX12/Vulkan in future), but this optimization was lost... but I tried to make comparator sort like in the original code.
Originally, sorting was performed with two criterias instead of just one: state change and SSA.
You can look at the original sorting code here: 5aeb5a64022628626688758d8a613d095511bddd. Maybe, you will be able to

**Comment by StathisKap** [comment]
hey @Lnd-stoL I've been trying to compile your fork of the engine and I haven't been able too. I get this error
```
-- CMAKE_SYSTEM_PROCESSOR: arm64
-- MASTER_GOLD: ON
-- STATIC_BUILD: ON
Using mimalloc memory allocator
CMake build Release, CFLAGS=  -mfpu=neon, CXXFLAGS= -fdelayed-template-parsing -Wno-unused-command-line-argument -Wno-inconsistent-missing-override -stdlib=libc++ -Wno-attributes -fvisibility=hidden -Wl,-undefined,error  -mfpu=neon
git commit: 5d1a79146dc1a229880af0c6981a6292eb54dc15
git branch: dev
CMake Error at Externals/LuaJIT-proj/luajit.cmake:169 (message):
  Unsupported luajit target architecture
Call Stack (most recent call first):
  Externals/LuaJIT-proj/CMakeLists.txt:1 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/stathis/Code/xray-16/build/CMakeFiles/CMakeOutput.log".
See also "/Users/stathis/Code/xray-16/build/CMakeFiles/CMakeError.log".
```

Do you know what I need to change?

**Comment by pkolchanov** [comment]
@StathisKap try to clone with submodules  

`git clone https://github.com/Lnd-stoL/xray-16.git --recurse-submodules`

**Comment by Lnd-stoL** [comment]
> hey @Lnd-stoL I've been trying to compile your fork of the engine and I haven't been able too. I get this error
> 
> ```
> -- CMAKE_SYSTEM_PROCESSOR: arm64
> -- MASTER_GOLD: ON
> -- STATIC_BUILD: ON
> Using mimalloc memory allocator
> CMake build Release, CFLAGS=  -mfpu=neon, CXXFLAGS= -fdelayed-template-parsing -Wno-unused-command-line-argument -Wno-inconsistent-missing-override -stdlib=libc++ -Wno-attributes -fvisibility=hidden -Wl,-undefined,error  -mfpu=neon
> git commit: 5d1a79146dc1a229880af0c6981a6292eb54dc15
> git branch: dev
> CMake Error at Externals/LuaJIT-proj/luajit.cmake:169 (message):
>   Unsupported luajit target architecture
> Call Stack (most recent call first):
>   Externals/LuaJIT-proj/CMakeLists.txt:1 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/stathis/Code/xray-16/build/CMakeFiles/CMakeOutput.log".
> See also "/Users/stathis/Code/xray-16/build/CMakeFiles/CMakeError.log".
> ```
> 
> Do you know what I need to change?

@StathisKap, I faced this issue too and managed to get around it doing some dirty hacks, and basically, disabling jit  in luajit via cmake option. I can’t publish these changes via PR cause they are hacks, but can share the diff which helped me to get luajit building.
As far as I know, latest luajit actually has support for Mac M1, so it maybe worth trying the latest version instead of the x-ray repository one. If this doesn’t help, the issue should be addressed to luajit developers.

**Comment by Xottab-DUTY** [comment]
Upstream LuaJIT won't work correctly with OpenXRay, we have applied custom patches to make it work...

File: src/Layers/xrRender/r__dsgraph_render.cpp (hunk 5 above)
Comment (Lnd-stoL) [reply src/Layers/xrRender/r__dsgraph_render.cpp]: The comment seems to be truncated, what was the question "Maybe, you will be able to")?

Comment (Lnd-stoL) [reply src/Layers/xrRender/r__dsgraph_render.cpp]: > Maybe it's better to move this particular change to another pull request

Sure, it's possible. But this change is absolutely required to run the game on macOS: without it the game crashes right at the beginning, rendering the first frame.

Comment (Lnd-stoL) [reply src/Layers/xrRender/r__dsgraph_render.cpp]: >  but I tried to make comparator sort like in the original code

As far as I can see the comparator is not like in the original code, but rather nonsense because of 

>  it returns true for two equal arguments, that means cmp(a, b) == cmp(b, a) if a.equal(b) or, in the other words, a < b && b < a is true

I'm pretty much surprised how it even works on windows and what are the resulting order of the items.

**Comment by Lnd-stoL** [comment]
> Upstream LuaJIT won't work correctly with OpenXRay, we have applied custom patches to make it work...

Hmm, so it must be possible to apply OpenXRay patches on top of the latest upstream LuaJIT?
Where are these patches? What is the reason for these patches?

**Comment by Xottab-DUTY** [comment]
> Where are these patches? What is the reason for these patches?

They are right in the fork as commits.
Main reason: original scripts were written for LuaJIT 1.1.x, while latest LuaJIT 2.1 has breaking behaviour changes and we have a restriction to not change game resources at all..

> Hmm, so it must be possible to apply OpenXRay patches on top of the latest upstream LuaJIT?

Maybe, I haven't work with git patches. 🙂

File: src/Layers/xrRender/r__dsgraph_render.cpp (hunk 5 above)
Comment (Xottab-DUTY) [reply src/Layers/xrRender/r__dsgraph_render.cpp]: @Lnd-stoL, so, with @vTurbine we have figured that we don't need stable sort here and it's better to return generic sort. Comparator change is ok and enough! 🙂

Comment (Lnd-stoL) [reply src/Layers/xrRender/r__dsgraph_render.cpp]: Ok, thanks for figuring that out.

**Review by Xottab-DUTY — APPROVED** [review]

**Comment by Xottab-DUTY** [comment]
Yay! Thank you!
