### PR TITLE
Fix build warnings in src/xrCore and src/Common

### LINKED ISSUE #713: Compiler warnings elimination
Starting from the creation of this task, #116 is a subtask of this task.

MSVC:
- [ ] MSBuild
  - [ ] Enable "warnings are errors" mode *(is it possible?)*
- [ ] Compiler
  - [x] Enable conformance mode
  - [x] Enable "warnings are errors" mode
  - [ ] Raise the warning level to 4
    - [x] Level 1
    - [x] Level 2
    - [ ] Level 3
    - [ ] Level 4
- [ ] Linker
  - [ ] Enable "warnings are errors" mode

GCC:
- CMake and `make`
  - [ ] Enable "warnings are errors" mode *(is it possible?)*
- [ ] Compiler
  - [x] Disable permissive mode
  - [ ] *Maybe enable [pedantic mode](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)*
  - [ ] Enable "warnings are errors" mode
  - [ ] Raise the warning level to 4
    - [ ] Level 1
    - [ ] Level 2
    - [ ] Level 3
    - [ ] Level 4
- [ ] Linker
  - [ ] Enable "warnings are errors" mode

For history:
- [ ] List all warnings elimination commits in this issue

Tools:
PVS-Studio
CppDepend (includes cppcheck, Clang-Tidy, Vera++)
ReSharper C++ (includes Clang and Clang-Tidy check plus it's own analysis)
Visual Assist (has it's own code inspection)

https://habr.com/ru/articles/75123/
https://habr.com/ru/companies/pvs-studio/articles/303664/

### PR DESCRIPTION
**Pull request by Masterkatze**
Part of #907

### CODE REVIEW

File: src/xrCore/Animation/BoneEditor.cpp [hunk 1]
```diff
@@ -23,26 +25,32 @@ void SJointIKData::clamp_by_limits(Fvector& dest_xyz)
...
+//        dest_xyz.x = 0;
+//        break;
+//    case jtWheelZX:
+//        clamp(dest_xyz.z, limits[2].limit.x, limits[2].limit.y);
+//        dest_xyz.y = 0;
+//        break;
+//    case jtWheelZY:
+//        clamp(dest_xyz.z, limits[2].limit.x, limits[2].limit.y);
+//        dest_xyz.x = 0;
+//        break;
```
Comment (Xottab-DUTY) [inline src/xrCore/Animation/BoneEditor.cpp]: Don't touch old code at all, preserving original formatting.

File: src/xrCore/FS.cpp [hunk 2]
```diff
@@ -169,7 +169,7 @@ void FileCompress(pcstr fn, pcstr sign, void* data, size_t size)
 
     int H = _open(fn, O_BINARY | O_CREAT | O_WRONLY | O_TRUNC, S_IREAD | S_IWRITE);
     R_ASSERT2(H > 0, fn);
-    _write(H, &M, 8);
+    [[maybe_unused]] auto write_result = _write(H, &M, 8);
```
Comment (Xottab-DUTY) [inline src/xrCore/FS.cpp]:
```suggestion
    std::ignore = _write(H, &M, 8);
```

File: src/xrCore/FS.cpp [hunk 3]
```diff
@@ -181,7 +181,7 @@ void* FileDecompress(pcstr fn, pcstr sign, size_t* size)
 
     int H = _open(fn, O_BINARY | O_RDONLY);
     R_ASSERT2(H > 0, fn);
-    _read(H, &F, 8);
+    [[maybe_unused]] auto read_result = _read(H, &F, 8);
```
Comment (Xottab-DUTY) [inline src/xrCore/FS.cpp]:
```suggestion
    std::ignore = _read(H, &F, 8);
```

File: src/xrCore/LocatorAPI.cpp [hunk 4]
```diff
@@ -199,7 +199,10 @@ const CLocatorAPI::file* CLocatorAPI::Register(
 {
     string256 temp_file_name;
     xr_strcpy(temp_file_name, sizeof temp_file_name, name);
+
+#if defined(XR_PLATFORM_WINDOWS)
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.cpp]: This changes behaviour! It should be in a separate pull-request, because it's not related to warning fixes.

File: src/xrCore/LocatorAPI.h [hunk 5]
```diff
@@ -148,10 +148,10 @@ class XRCORE_API CLocatorAPI : Noncopyable
     void check_pathes();
 
     files_set m_files;
-    bool bNoRecurse;
+    bool bNoRecurse{true};
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.h]:
```suggestion
    bool bNoRecurse{ true };
```

File: src/xrCore/LocatorAPI.h [hunk 6]
```diff
@@ -148,10 +148,10 @@ class XRCORE_API CLocatorAPI : Noncopyable
...
 
     Lock* m_auth_lock;
-    u64 m_auth_code;
+    u64 m_auth_code{0};
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.h]:
```suggestion
    u64 m_auth_code{};
```

File: src/xrCore/fastdelegate.h [hunk 7]
```diff
@@ -134,9 +134,9 @@ inline OutputClass horrible_cast(const InputClass input)
     // Cause a compile-time error if in, out and u are not the same size.
     // If the compile fails here, it means the compiler has peculiar
     // unions which would prevent the cast from working.
-    typedef int
-        ERROR_CantUseHorrible_cast[sizeof(InputClass) == sizeof(u) && sizeof(InputClass) == sizeof(OutputClass) ? 1 :
-                                                                                                                  -1];
+    static_assert(sizeof(InputClass) == sizeof(u));
+    static_assert(sizeof(InputClass) == sizeof(OutputClass));
```
Comment (Xottab-DUTY) [inline src/xrCore/fastdelegate.h]:
```suggestion
    static_assert(sizeof(InputClass) == sizeof(u),           "Can't use horrible cast.");
    static_assert(sizeof(InputClass) == sizeof(OutputClass), "Can't use horrible cast.");
```

File: src/xrCore/fastdelegate.h [hunk 8]
```diff
@@ -207,7 +207,7 @@ struct SimplifyMemFunc
     {
         // Unsupported member function type -- force a compile failure.
         // (it's illegal to have a array with negative size).
-        typedef char ERROR_Unsupported_member_function_pointer_on_this_compiler[N - 100];
+        static_assert(N - 100);
```
Comment (Xottab-DUTY) [inline src/xrCore/fastdelegate.h]: Осуждаю xD
```suggestion
        static_assert(false, "Unsupported member function pointer on this compiler.");
```

File: src/xrCore/file_stream_reader.cpp [hunk 9]
```diff
@@ -37,8 +37,10 @@ void CFileStreamReader::destroy()
     CloseHandle(file_mapping_handle);
     CloseHandle(m_file_handle);
 #elif defined(XR_PLATFORM_LINUX)
-    int file_mapping_handle = this->file_mapping_handle();
```
Comment (Xottab-DUTY) [inline src/xrCore/file_stream_reader.cpp:40]: Behaviour should not be changed in a "polishing" PR, unless it's clearly fixes a warning that indicates a real bug.
Did the compiler thew warnings here?

I think, it's better not to change the code here, but we can leave `XXX` to look at it later or in another PR :)

File: src/xrCore/net_utils.h [hunk 10]
```diff
@@ -79,21 +79,20 @@ struct NET_Buffer
 class XRCORE_API NET_Packet
 {
 public:
-    IIniFileStream* inistream;
+    IIniFileStream* inistream{nullptr};
```
Comment (Xottab-DUTY) [inline src/xrCore/net_utils.h]:
```suggestion
    IIniFileStream* inistream{};
```

File: src/xrCore/net_utils.h [hunk 11]
```diff
@@ -79,21 +79,20 @@ struct NET_Buffer
...
     }
 
-    NET_Buffer B;
-    u32 r_pos;
-    u32 timeReceive;
-    bool w_allow;
+    NET_Buffer B{};
+    u32 r_pos{0};
+    u32 timeReceive{0};
+    bool w_allow{true};
```
Comment (Xottab-DUTY) [inline src/xrCore/net_utils.h]:
```suggestion
    u32 r_pos{};
    u32 timeReceive{};
    bool w_allow{ true };
```

File: src/xrCore/xr_cpuid.cpp [hunk 12]
```diff
@@ -194,10 +194,10 @@ bool query_processor_info(processor_info* pinfo)
     }*/
 
     nativeCpuId(cpui.data(), 0x80000000);
-    const int nExIds_ = cpui[0];
+    const unsigned int nExIds_ = cpui[0];
     data.clear();
 
-    for (int i = 0x80000000; i <= nExIds_; ++i)
+    for (unsigned int i = 0x80000000; i <= nExIds_; ++i)
```
Comment (Xottab-DUTY) [inline src/xrCore/xr_cpuid.cpp]: Not sure... Maybe we can make it u32... :)

File: src/Common/PlatformLinux.inl [hunk 13]
```diff
@@ -1085,7 +1085,13 @@ typedef void *HIC;
 
 inline BOOL SwitchToThread() { return (0 == sched_yield()); }
 
-#define xr_fs_strlwr(str) str
+template<typename T>
```
Comment (Xottab-DUTY) [inline src/Common/PlatformLinux.inl]:
```suggestion
template <typename T>
```

Comment (Xottab-DUTY) [reply src/Common/PlatformLinux.inl]: Also, please, add `do_nothing` to PlatformBSD.inl :)

File: src/xrCore/_bitwise.h [hunk 14]
```diff
@@ -101,20 +100,23 @@ IC int iCeil(float x)
     return static_cast<int>(std::ceil(x));
 }
 
+
```
Comment (Xottab-DUTY) [inline src/xrCore/_bitwise.h]:
```suggestion
```

File: src/xrCore/_bitwise.h [hunk 15]
```diff
@@ -101,20 +100,23 @@ IC int iCeil(float x)
...
 IC bool fis_denormal(const float& f) { return !(*(int*)&f & 0x7f800000); }
+
 // Approximated calculations
-IC float apx_InvSqrt(const float& n)
-{
-    long tmp = (long(0xBE800000) - *(long*)&n) >> 1;
-    float y = *(float*)&tmp;
-    return y * (1.47f - 0.47f * n * y * y);
-}
+//IC float apx_InvSqrt(const float& n)
```
Comment (Xottab-DUTY) [inline src/xrCore/_bitwise.h]: This function is not used, let's just delete it.

File: src/xrCore/file_stream_reader.cpp (hunk 9 above)
Comment (Xottab-DUTY) [reply src/xrCore/file_stream_reader.cpp:40]: Yeah, sorry, we figured out in Discord that I have misread the code.

File: src/xrCore/_bitwise.h (hunk 15 above)
Comment (Xottab-DUTY) [reply src/xrCore/_bitwise.h]: :D
image

File: src/xrCore/LocatorAPI.cpp [hunk 16]
```diff
@@ -416,7 +417,7 @@ void CLocatorAPI::LoadArchive(archive& A, pcstr entrypoint)
             int count = sscanf(read_path.c_str(), "%[^\\]s", alias_name);
             R_ASSERT2(count == 1, read_path.c_str());
 
-            auto P = m_paths.find(alias_name);
+            // auto P = m_paths.find(alias_name);
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.cpp]: Looked at the vanilla code, this variable was used in the past. Look like, I forgot to remove it after refactoring. Let's just remove it :)
```suggestion
```

File: src/xrCore/file_stream_reader.cpp (hunk 9 above)
Comment (Xottab-DUTY) [reply src/xrCore/file_stream_reader.cpp:40]: @Masterkatze, but what about leaving the comment, like: `XXX: maybe, we should close the handle` ?

Comment (Masterkatze) [reply src/xrCore/file_stream_reader.cpp:40]: @Xottab-DUTY we open file_mapping_handle only on Windows (line 15), so everything is in place now, no changes needed.

File: src/xrCore/LocatorAPI.cpp [hunk 17]
```diff
@@ -948,8 +946,8 @@ void CLocatorAPI::_initialize(u32 flags, pcstr target_folder, pcstr fs_name)
             _GetItem(temp, 4, def, _delimiter);
             _GetItem(temp, 5, capt, _delimiter);
             xr_strlwr(id);
-
             xr_fs_strlwr(root);
+
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.cpp]:
```suggestion
```

File: src/xrCore/LocatorAPI.cpp [hunk 18]
```diff
@@ -948,8 +946,8 @@ void CLocatorAPI::_initialize(u32 flags, pcstr target_folder, pcstr fs_name)
             _GetItem(temp, 4, def, _delimiter);
             _GetItem(temp, 5, capt, _delimiter);
             xr_strlwr(id);
-
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.cpp]: Revert this

File: src/xrCore/LocatorAPI.cpp [hunk 19]
```diff
@@ -199,6 +199,7 @@ const CLocatorAPI::file* CLocatorAPI::Register(
 {
     string256 temp_file_name;
     xr_strcpy(temp_file_name, sizeof temp_file_name, name);
+
```
Comment (Xottab-DUTY) [inline src/xrCore/LocatorAPI.cpp]:
```suggestion
```

File: src/xrCore/Compression/Model.cpp [hunk 20]
```diff
@@ -1250,8 +1250,6 @@ static void _STDCALL StartModelRare(int MaxOrder, MR_METHOD MRMethod)
     }
     else
     {
-        u32 i, k, m;
-
```
Comment (Xottab-DUTY) [inline src/xrCore/Compression/Model.cpp]: Let's comment it like this:
```cpp
///        u32 i, k, m;
```

image

**Review by Xottab-DUTY — APPROVED** [review]
