### PR TITLE
Fix unpredictable console cursor behaviour (closes #1356)

### LINKED ISSUE #1356: Unpredictable cursor behavior when holding left arrow key
**Describe the bug**
In console, the behavior of the cursor to the left is unpredictable and cycles from right to left, but the behavior of the cursor to the right is predictable and it rests on the size of the string

**To Reproduce**
1. Watch video

**Expected behavior**

**Video**

https://github.com/OpenXRay/xray-16/assets/21138600/bcc42b56-8aca-49b4-863a-050fab088daf

**Desktop:**
 - OS: any
 - OpenXRay

### PR DESCRIPTION
**Pull request by NikDy**
cursor jump was caused by variable overflow
issue [#1356](https://github.com/OpenXRay/xray-16/issues/1356)

### CODE REVIEW

File: src/xrEngine/line_edit_control.cpp [hunk 1]
```diff
@@ -632,21 +632,21 @@ void line_edit_control::delete_word_forward()
...
 
-    if (!terminate_char(m_edit_str[i]))
+    if (i > 0 && !terminate_char(m_edit_str[i]))
     {
-        while (i >= 0 && !terminate_char(m_edit_str[i], true))
+        while (i > 0 && !terminate_char(m_edit_str[i], true))
             --i;
 
-        ++i;
+        if (i > 0) ++i;
```
Comment (Xottab-DUTY) [inline src/xrEngine/line_edit_control.cpp]:
```suggestion
        if (i > 0)
            ++i;
```

File: src/xrEngine/line_edit_control.cpp [hunk 2]
```diff
@@ -632,21 +632,21 @@ void line_edit_control::delete_word_forward()
 
 void line_edit_control::move_pos_home() { m_cur_pos = 0; }
 void line_edit_control::move_pos_end() { m_cur_pos = xr_strlen(m_edit_str); }
-void line_edit_control::move_pos_left() { --m_cur_pos; }
+void line_edit_control::move_pos_left() { if(m_cur_pos > 0) --m_cur_pos; }
```
Comment (Xottab-DUTY) [inline src/xrEngine/line_edit_control.cpp]:
```suggestion
void line_edit_control::move_pos_left()
{
    if (m_cur_pos > 0)
        --m_cur_pos;
}
```

**Review by Xottab-DUTY — APPROVED** [review]

**Comment by Xottab-DUTY** [comment]
Thanks!
