### PR TITLE
Fix build warnings in src/xrGame

### LINKED ISSUE #713: Compiler warnings elimination
Starting from the creation of this task, #116 is a subtask of this task.

MSVC:
- [ ] MSBuild
  - [ ] Enable "warnings are errors" mode *(is it possible?)*
- [ ] Compiler
  - [x] Enable conformance mode
  - [x] Enable "warnings are errors" mode
  - [ ] Raise the warning level to 4
    - [x] Level 1
    - [x] Level 2
    - [ ] Level 3
    - [ ] Level 4
- [ ] Linker
  - [ ] Enable "warnings are errors" mode

GCC:
- CMake and `make`
  - [ ] Enable "warnings are errors" mode *(is it possible?)*
- [ ] Compiler
  - [x] Disable permissive mode
  - [ ] *Maybe enable [pedantic mode](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)*
  - [ ] Enable "warnings are errors" mode
  - [ ] Raise the warning level to 4
    - [ ] Level 1
    - [ ] Level 2
    - [ ] Level 3
    - [ ] Level 4
- [ ] Linker
  - [ ] Enable "warnings are errors" mode

For history:
- [ ] List all warnings elimination commits in this issue

Tools:
PVS-Studio
CppDepend (includes cppcheck, Clang-Tidy, Vera++)
ReSharper C++ (includes Clang and Clang-Tidy check plus it's own analysis)
Visual Assist (has it's own code inspection)

https://habr.com/ru/articles/75123/
https://habr.com/ru/companies/pvs-studio/articles/303664/

### PR DESCRIPTION
**Pull request by Masterkatze**

### CODE REVIEW

File: src/xrGame/ui/UIMotionIcon.cpp [hunk 1]
```diff
@@ -87,43 +87,22 @@ bool CUIMotionIcon::Init(Frect const& zonemap_rect)
...
-    }
-
-    if ((state = UIHelper::CreateStatic(uiXml, "state_creep", this, false)))
-    {
-        m_states[stCreep] = state;
-        state->Show(false);
-    }
-
-    if ((state = UIHelper::CreateStatic(uiXml, "state_climb", this, false)))
+    auto crate_static = [&uiXml, this](LPCSTR ui_path, EState state)
```
Comment (Xottab-DUTY) [inline src/xrGame/ui/UIMotionIcon.cpp]:
```suggestion
    const auto create_static = [&uiXml, this](pcstr ui_path, EState state)
```

File: src/xrGame/ui/UICharacterInfo.h [hunk 2]
```diff
@@ -52,7 +52,7 @@ class CUICharacterInfo : public CUIWindow
         eMaxCaption
     };
     CUIStatic* m_icons[eMaxCaption];
-    shared_str m_texture_name;
+    shared_str m_texture_name{};
```
Comment (Xottab-DUTY) [inline src/xrGame/ui/UICharacterInfo.h]: If I'm correct, this is not needed, because shared_str has a constructor.

File: src/xrGame/ui/UIChangeMap.cpp [hunk 3]
```diff
@@ -130,7 +130,7 @@ void CUIChangeMap::OnBtnOk()
 {
     u32 idx = lst->GetSelectedIDX();
     const SGameTypeMaps& M = gMapListHelper.GetMapListFor((EGameIDs)GameID());
-    if (idx >= 0 && idx < M.m_map_names.size())
+    if (idx < M.m_map_names.size())
```
Comment (Xottab-DUTY) [inline src/xrGame/ui/UIChangeMap.cpp:133]: ~~now `0` (zero) index won't work, but it was working previously.~~
Oh, oops, I've got mixed up.

File: src/xrGame/trade_factor_parameters_inline.h [hunk 4]
```diff
@@ -12,7 +12,7 @@ IC CTradeFactorParameters::CTradeFactorParameters() {}
 IC void CTradeFactorParameters::clear() { m_factors.clear(); }
 IC void CTradeFactorParameters::enable(const shared_str& section, const CTradeFactors& factors)
 {
-    FACTORS::const_iterator I = m_factors.find(section);
+    [[maybe_unused]] auto I = m_factors.find(section);
     VERIFY(I == m_factors.end());
```
Comment (Xottab-DUTY) [inline src/xrGame/trade_factor_parameters_inline.h]: Currently, this debug check gets into production code and working without doing anything useful on release configurations.
Lets keep it debug only.
```suggestion
    VERIFY(m_factors.find(section) == m_factors.end());
```

File: src/xrGame/trade_bool_parameters_inline.h [hunk 5]
```diff
@@ -12,13 +12,13 @@ IC CTradeBoolParameters::CTradeBoolParameters() {}
 IC void CTradeBoolParameters::clear() { m_sections.clear(); }
 IC void CTradeBoolParameters::disable(const shared_str& section)
 {
-    SECTIONS::iterator I = std::find(m_sections.begin(), m_sections.end(), section);
+    [[maybe_unused]] auto I = std::find(m_sections.begin(), m_sections.end(), section);
     VERIFY(I == m_sections.end());
```
Comment (Xottab-DUTY) [inline src/xrGame/trade_bool_parameters_inline.h]:
```suggestion
    VERIFY(std::find(m_sections.begin(), m_sections.end(), section) == m_sections.end());
```

File: src/xrGame/stalker_movement_params.h [hunk 6]
```diff
@@ -92,34 +92,34 @@ class stalker_movement_params
...
-    shared_str m_cover_loophole_id;
-    loophole_type const* m_cover_loophole;
+    shared_str m_cover_loophole_id{""};
+    loophole_type const* m_cover_loophole{};
 
-    CGameObject const* m_cover_fire_object;
-    Fvector m_cover_fire_position_impl;
-    Fvector const* m_cover_fire_position;
+    CGameObject const* m_cover_fire_object{};
+    Fvector m_cover_fire_position_impl{Fvector().set(flt_max, flt_max, flt_max)};
```
Comment (Xottab-DUTY) [inline src/xrGame/stalker_movement_params.h]: Please, add spaces:
```suggestion
    Fvector m_cover_fire_position_impl{ Fvector().set(flt_max, flt_max, flt_max) };
```

File: src/xrGame/ActorCondition.cpp [hunk 7]
```diff
@@ -643,12 +643,9 @@ void CActorCondition::DisableBoostParameters(const SBooster& B)
...
 void CActorCondition::WoundForEach(const luabind::functor<bool>& funct)
 {
-    auto const& cur_wounds = wounds();
-    CEntityCondition::WOUND_VECTOR::const_iterator it = wounds().begin();
-    CEntityCondition::WOUND_VECTOR::const_iterator it_e = wounds().end();
-    for (; it != it_e; ++it)
+    for (auto it = wounds().begin(); it != wounds().end(); ++it)
     {
-        if (funct(it) == true)
+        if (funct(it))
```
Comment (Xottab-DUTY) [inline src/xrGame/ActorCondition.cpp]: ~~This functor accepts bool, but we are sending an iterator to it.
Something is wrong...~~
Ah, it returns bool :)

~~Also, keeping `end()` as `it_e` variable is still better, because `wounds().end()` will be called each time.~~
The last is wrong :)

File: src/xrGame/CustomRocket.cpp [hunk 8]
```diff
@@ -408,18 +408,24 @@ void CCustomRocket::UpdateCL()
...
+    {
+        UpdateEngine();
+        [[fallthrough]];
+    }
     case eFlying:
+    {
         UpdateLights();
         UpdateParticles();
         break;
     }
```
Comment (Xottab-DUTY) [inline src/xrGame/CustomRocket.cpp]:
```suggestion
    case eEngine:
        UpdateEngine();
        [[fallthrough]];

    case eFlying:
        UpdateLights();
        UpdateParticles();
        break;
```

File: src/xrGame/CustomRocket.cpp [hunk 9]
```diff
@@ -408,18 +408,24 @@ void CCustomRocket::UpdateCL()
...
+    }
     if (m_eState == eEngine || m_eState == eFlying)
     {
         if (m_time_to_explode < Device.fTimeGlobal)
         {
             Contact(Position(), Direction());
-            //			Msg("--contact");
+            //Msg("--contact");
```
Comment (Xottab-DUTY) [inline src/xrGame/CustomRocket.cpp]:
```suggestion
            // Msg("--contact");
```

File: src/xrGame/Entity.cpp [hunk 10]
```diff
@@ -101,7 +101,7 @@ void CEntity::Hit(SHit* pHDS)
     // *** process hit calculations
     // Calc impulse
     Fvector vLocalDir;
-    float m = pHDS->dir.magnitude();
+    [[maybe_unused]] float m = pHDS->dir.magnitude();
     VERIFY(m > EPS);
```
Comment (Xottab-DUTY) [inline src/xrGame/Entity.cpp]:
```suggestion
    VERIFY(pHDS->dir.magnitude() > EPS);
```
