### PR TITLE
Sanitize `UserName` and `CompName`

### LINKED ISSUE #1536: On Linux, quick save are being created in a subfolder instead of game saves folder
**Describe the bug**
When you use a quick save, the file name is `<system name> - quicksave.<fmt>`, where \<system name\> is the user profile name in the OS and \<fmt\> is file format – either `scop` or `sav`.

For some reason, when we try to save a file with path `game folder/_appdata_/savedgames/user - quicksave.scop`, the result appears to be `game folder/_appdata_/gamesaves/user/- quicksave.scop` – it creates a subfolder.

**To Reproduce**
1. Use a quick save
2. See the bug

**Expected behavior**
Quick saves should be saved into savedgames folder normally.

**Screenshots, videos**
image
image

**Desktop (please complete the following information):**
 - OS: any Linux
 - OpenXRay latest

**Additional context**
Look at function `CALifeStorageManager::save` in `xrGame/alife_storage_manager.cpp`

### PR DESCRIPTION
**Pull request by AMS21**
Question are there any more problematic characters we need to fix?

My attempt to fix #1536

### CODE REVIEW

**Comment by AMS21** [comment]
@Xottab-DUTY Could you test this patch if it fixes your problem?

File: src/xrCore/xrCore.cpp [hunk 1]
```diff
@@ -65,6 +65,27 @@ const pcstr xrCore::buildDate = __DATE__;
...
+            case '/':
+            case ',':
+            case '.':
+                *mut_str = '_';
+                [[fallthrough]];
+
+            default:
+                ++mut_str;
+        }
+    }
```
Comment (Xottab-DUTY) [inline src/xrCore/xrCore.cpp]:
```suggestion
    while (*mut_str != '\0')
    {
        switch (*mut_str)
        {
        case '\\':
        case '/':
        case ',':
        case '.':
            *mut_str = '_';
            [[fallthrough]];
        default:
            ++mut_str;
        }
    }
```

File: src/xrCore/xrCore.cpp [hunk 2]
```diff
@@ -221,21 +242,31 @@ void xrCore::Initialize(pcstr _ApplicationName, pcstr commandLine, LogCallback c
...
+        if (pw)
         {
-            strcpy(UserName, pw->pw_gecos);
-            char* pos = strchr(UserName, ','); // pw_gecos return string
-            if(NULL != pos)
-                *pos = 0;
-            if(0 == UserName[0])
-                strcpy(UserName, pw->pw_name);
+            strncpy(UserName, pw->pw_gecos, sizeof(UserName) - 1);
+            if(UserName[0] == '\0')
```
Comment (Xottab-DUTY) [inline src/xrCore/xrCore.cpp]:
```suggestion
            if (UserName[0] == '\0')
```

**Review by Xottab-DUTY — APPROVED** [review]
